// Maps Hawdex --t-* inline tokens to canonical tokens.css variables.
// The existing THEMES objects in App.tsx inject --t-* via inline style.
// This file bridges those to our CSS custom properties from tokens.css.
export const HAWDEX_PRECISION: Record<string, string> = {
  "--t-bg":        "var(--background)",
  "--t-surface":   "var(--card)",
  "--t-surface2":  "var(--muted)",
  "--t-border":    "var(--border-default)",
  "--t-border2":   "var(--border-subtle)",
  "--t-text1":     "var(--foreground)",
  "--t-text2":     "var(--muted-foreground)",
  "--t-text3":     "var(--text-tertiary)",
  "--t-hdr":       "var(--card)",
  "--t-sidebar":   "var(--sidebar)",
  "--t-nav-act":   "var(--sidebar-accent)",
  "--t-nav-c-act": "var(--primary)",
  "--t-nav-c":     "var(--muted-foreground)",
  "--t-nav-bdr":   "var(--primary)",
  "--t-primary":   "var(--primary)",
  "--t-primary-s": "var(--primary-50)",
  "--t-teal":      "var(--secondary-600)",
  "--t-teal-s":    "var(--secondary-50)",
  "--t-radius":    "10px",
  "--t-shadow":    "var(--depth-2)",
  "--t-shadow3":   "var(--depth-3)",
  "--t-dot":       "var(--primary)",
  "--t-icon-bg":   "var(--primary-50)",
  "--t-icon-c":    "var(--primary)",
  "--t-icon-ai-bg":"var(--tertiary-900)",
  "--t-icon-ai-c": "var(--primary-foreground)",
  "--t-icon-tl-bg":"var(--secondary-50)",
  "--t-icon-tl-c": "var(--text-teal)",
  "--t-tag-bg":    "var(--primary-50)",
  "--t-tag-c":     "var(--primary)",
  "--t-tag-bdr":   "var(--border-primary)",
  "--t-input-bg":  "var(--card)",
  "--t-gamify":    "var(--tertiary-900)",
  "--t-blur":      "16px",
} as const;

export const HAWDEX_OBSIDIAN: Record<string, string> = {
  "--t-bg":        "#060E1A",
  "--t-surface":   "var(--card)",
  "--t-surface2":  "var(--muted)",
  "--t-border":    "var(--border-default)",
  "--t-border2":   "var(--border-subtle)",
  "--t-text1":     "var(--foreground)",
  "--t-text2":     "var(--text-secondary)",
  "--t-text3":     "var(--text-tertiary)",
  "--t-hdr":       "var(--card)",
  "--t-sidebar":   "var(--sidebar)",
  "--t-nav-act":   "rgba(26,155,213,0.12)",
  "--t-nav-c-act": "var(--primary)",
  "--t-nav-c":     "var(--text-secondary)",
  "--t-nav-bdr":   "var(--primary)",
  "--t-primary":   "var(--primary)",
  "--t-primary-s": "rgba(26,155,213,0.14)",
  "--t-teal":      "var(--secondary)",
  "--t-teal-s":    "rgba(74,173,168,0.12)",
  "--t-radius":    "12px",
  "--t-shadow":    "var(--depth-2)",
  "--t-shadow3":   "var(--depth-3)",
  "--t-dot":       "var(--primary)",
  "--t-icon-bg":   "rgba(26,155,213,0.16)",
  "--t-icon-c":    "var(--primary)",
  "--t-icon-ai-bg":"rgba(26,155,213,0.22)",
  "--t-icon-ai-c": "var(--foreground)",
  "--t-icon-tl-bg":"rgba(74,173,168,0.16)",
  "--t-icon-tl-c": "var(--secondary)",
  "--t-tag-bg":    "rgba(26,155,213,0.12)",
  "--t-tag-c":     "var(--primary)",
  "--t-tag-bdr":   "rgba(26,155,213,0.18)",
  "--t-input-bg":  "var(--card)",
  "--t-gamify":    "#0D1F3B",
  "--t-blur":      "20px",
} as const;