#!/usr/bin/env bash
# Runs scripts/infra-health-report.sql against the linked Supabase project and
# archives a timestamped JSON snapshot under audit/baselines/infra-health/.
# See infra-health-report.ps1 header for the full rationale and section list.
#
# Usage:
#   bash scripts/infra-health-report.sh
#   SUPABASE_PROJECT_ID=<other-id> bash scripts/infra-health-report.sh
#   bash scripts/infra-health-report.sh --no-save     # print only, don't archive
#
# Requires: Supabase CLI auth (same prerequisite as scripts/regen-types.sh),
# and node (already a project dependency) for JSON parsing/formatting.

set -uo pipefail

PROJECT_ID="${SUPABASE_PROJECT_ID:-cdlgtbvxlxjpcddjazzx}"
NO_SAVE=0
for arg in "$@"; do
  [ "$arg" = "--no-save" ] && NO_SAVE=1
done

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$ROOT" ]; then echo "FAIL not in a git repo" >&2; exit 1; fi
cd "$ROOT"

SQL_FILE="scripts/infra-health-report.sql"
if [ ! -f "$SQL_FILE" ]; then
  echo "FAIL $SQL_FILE not found" >&2
  exit 1
fi

echo "[infra-health] checking Supabase auth..."
if ! npx --yes -p supabase@latest supabase projects list --output json >/dev/null 2>&1; then
  echo "FAIL Supabase CLI not authenticated." >&2
  echo "  fix: npx supabase login   (or export SUPABASE_ACCESS_TOKEN=...)" >&2
  exit 2
fi
echo "OK   authenticated"

echo "[infra-health] querying project $PROJECT_ID..."
RAW_FILE="$(mktemp)"
ERR_FILE="$(mktemp)"
cleanup() { rm -f "$RAW_FILE" "$ERR_FILE"; }
trap cleanup EXIT

if ! npx --yes -p supabase@latest supabase db query --file "$SQL_FILE" --linked --output json >"$RAW_FILE" 2>"$ERR_FILE"; then
  echo "FAIL query failed" >&2
  cat "$ERR_FILE" >&2
  exit 3
fi

if [ ! -s "$RAW_FILE" ]; then
  echo "FAIL query returned no output -- refusing to archive garbage" >&2
  exit 4
fi
echo "OK   snapshot captured"

# ── Human-readable summary + archive, via node (avoids a jq dependency) ─────
node - "$RAW_FILE" "$PROJECT_ID" "$NO_SAVE" "$ROOT" <<'NODE_EOF'
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const [, , rawFile, projectId, noSaveFlag, root] = process.argv;
const noSave = noSaveFlag === "1";

let parsed;
try {
  parsed = JSON.parse(fs.readFileSync(rawFile, "utf8"));
} catch (e) {
  console.error("FAIL could not parse CLI output as JSON:", e.message);
  process.exit(4);
}

const snapshot = parsed?.[0]?.infra_health_snapshot;
if (!snapshot || !snapshot.computeFingerprint) {
  console.error("FAIL query returned no snapshot -- refusing to archive garbage");
  process.exit(4);
}

console.log("");
console.log("=== Infra Health Summary ===");
console.log(`  shared_buffers:  ${snapshot.computeFingerprint.shared_buffers_8kb_pages} (8kB pages) -- see docs/operations/supabase-compute-tiers.md for tier lookup`);
console.log(`  max_connections: ${snapshot.computeFingerprint.max_connections}`);
console.log(`  connections now: ${snapshot.connectionHeadroom.current_connections} / ${snapshot.connectionHeadroom.max_connections} (${snapshot.connectionHeadroom.pct_used}%)`);
console.log(`  realtime published tables: ${snapshot.realtimePublishedTables.published_table_count}`);
console.log(`  tables with multiple permissive policies: ${(snapshot.multiplePermissivePolicies || []).length}`);
console.log(`  policies with a remaining bare auth call:  ${(snapshot.bareAuthCallsInRls || []).length}`);
console.log(`  SECURITY DEFINER RPCs exposed to anon/authenticated: ${(snapshot.securityDefinerRpcExposure || []).length}`);
console.log(`  extensions in public schema: ${(snapshot.extensionsInPublicSchema || []).map((e) => e.extname).join(", ")}`);
const top = (snapshot.topQueriesByTotalTime || [])[0];
if (top) {
  console.log(`  hottest query (by total time): ${top.calls} calls, mean ${top.mean_exec_time_ms}ms, max ${top.max_exec_time_ms}ms`);
}
console.log("");

if (noSave) {
  console.log("[infra-health] --no-save set, not archiving.");
  process.exit(0);
}

const outDir = path.join(root, "audit", "baselines", "infra-health");
fs.mkdirSync(outDir, { recursive: true });

let commit = "unknown";
try {
  commit = execSync("git rev-parse HEAD", { cwd: root }).toString().trim();
} catch {
  // leave as "unknown"
}

const timestamp = new Date().toISOString().slice(0, 10);
const outFile = path.join(outDir, `${timestamp}.json`);

const envelope = {
  createdAt: new Date().toISOString(),
  lockedByCommit: commit,
  description:
    "Point-in-time infra health snapshot (compute fingerprint, RLS multiplicity, hot queries, read amplification, security exposure). Generated by scripts/infra-health-report.sh. Informational history, not an enforced regression gate -- compare successive files by hand or with a future diff tool.",
  projectId,
  snapshot,
};

fs.writeFileSync(outFile, JSON.stringify(envelope, null, 2) + "\n", "utf8");
console.log(`OK   snapshot saved to ${path.relative(root, outFile)}`);
NODE_EOF

exit $?
