-- ============================================================
-- Migration: Create tutor_plan_updates table
-- Learning plan update suggestions generated by the AI tutor
-- ============================================================

-- Guard: skip if table already exists (idempotent)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'tutor_plan_updates'
  ) THEN
    RAISE NOTICE 'Table tutor_plan_updates already exists — skipping creation';
    RETURN;
  END IF;

  CREATE TABLE tutor_plan_updates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID NOT NULL REFERENCES profiles(id),
    institution_id UUID NOT NULL REFERENCES institutions(id),
    course_id UUID NOT NULL REFERENCES courses(id),
    clo_id UUID NOT NULL,
    conversation_id UUID NOT NULL REFERENCES tutor_conversations(id),
    study_time_recommendation TEXT NOT NULL,
    recommended_materials JSONB NOT NULL DEFAULT '[]',
    suggested_planner_sessions INTEGER NOT NULL DEFAULT 1,
    interaction_count INTEGER NOT NULL,
    response VARCHAR(20) CHECK (response IN ('accepted', 'modified', 'dismissed')),
    modifications TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    responded_at TIMESTAMPTZ
  );

  -- Index for querying student plan updates by CLO, ordered by recency
  CREATE INDEX idx_plan_updates_student_clo
    ON tutor_plan_updates (student_id, clo_id, created_at DESC);

  -- Enable RLS
  ALTER TABLE tutor_plan_updates ENABLE ROW LEVEL SECURITY;

  -- Student can read and update their own plan update records
  CREATE POLICY "plan_updates_student_select" ON tutor_plan_updates
    FOR SELECT TO authenticated
    USING (student_id = (select auth.uid()));

  CREATE POLICY "plan_updates_student_update" ON tutor_plan_updates
    FOR UPDATE TO authenticated
    USING (student_id = (select auth.uid()));

  -- Service role has full access (used by Edge Functions via SUPABASE_SERVICE_ROLE_KEY)
  -- Service role bypasses RLS by default, so no explicit policy needed.

END $$;
