// @vitest-environment node
// Pilot writer checks only: not DTCG Resolver support or browser accessibility.
import { afterEach, describe, expect, it } from "vitest";
import {
  mkdtempSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import {
  buildPortableColors,
  extractSelectedColors,
  runPortableColors,
  NAMES,
  SOURCE,
  OUTPUT,
  FORMAT,
} from "../../../scripts/design-tokens/export.mjs";

const fixtureCss = () =>
  [
    ":root {",
    ...NAMES.map((name) => `  --${name}: #112233;`),
    "}",
    ".dark {",
    ...NAMES.map((name) => `  --${name}: #aabbcc;`),
    "}",
    ":root { --unrelated-domain: 10px; }",
  ].join("\n");
const directories: string[] = [];
const fixture = (css = fixtureCss()) => {
  const root = mkdtempSync(join(tmpdir(), "edeviser-portable-tokens-"));
  directories.push(root);
  const source = join(root, SOURCE),
    output = join(root, OUTPUT);
  mkdirSync(dirname(source), { recursive: true });
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(source, css, "utf8");
  return { root, source, output };
};
afterEach(() => {
  for (const dir of directories.splice(0))
    rmSync(dir, { recursive: true, force: true });
});

describe("PR04 portable colors have one CSS authoring source", () => {
  it("emits 16 explicit DTCG color objects, not untyped CSS hex strings", () => {
    const snapshot = buildPortableColors(fixtureCss());
    expect(FORMAT).toBe("https://www.designtokens.org/TR/2025.10/format/");
    expect(snapshot.$extensions["org.edeviser.portablePilot"].source).toBe(
      SOURCE
    );
    for (const scope of ["light", "dark"] as const) {
      expect(Object.keys(snapshot.semantic[scope])).toEqual(NAMES);
      for (const token of Object.values(snapshot.semantic[scope])) {
        expect(token.$type).toBe("color");
        expect(token.$value.colorSpace).toBe("srgb");
        expect(token.$value.components).toHaveLength(3);
        expect(
          token.$value.components.every(
            (channel) => channel >= 0 && channel <= 1
          )
        ).toBe(true);
        const hex = `#${token.$value.components
          .map((channel) =>
            Math.round(channel * 255)
              .toString(16)
              .padStart(2, "0")
          )
          .join("")}`;
        expect(hex).toBe(token.$value.hex);
      }
    }
    expect(snapshot.semantic.light.card.$value.hex).toBe("#112233");
    expect(snapshot.semantic.dark.card.$value.hex).toBe("#aabbcc");
  });

  it("normalizes only physical CRLF/LF and ignores comment-only fake tokens", () => {
    const source = `/* :root { --primary: var(--fake); } */\n${fixtureCss()}`;
    expect(buildPortableColors(source)).toEqual(
      buildPortableColors(source.replace(/\n/g, "\r\n"))
    );
    expect(extractSelectedColors(source).light.primary).toBe("#112233");
  });

  it.each([
    ["alias", "var(--brand-primary)"],
    ["alpha", "rgba(1, 2, 3, 0.5)"],
    ["short hex", "#abc"],
    ["contextual layout", "calc(100% - 2rem)"],
  ])("rejects %s in a selected portable color", (_kind, value) => {
    expect(() =>
      extractSelectedColors(
        fixtureCss().replace("--primary: #112233", `--primary: ${value}`)
      )
    ).toThrow("literal opaque six-digit hex");
  });

  it("rejects duplicate and missing selected declarations instead of choosing CSS cascade", () => {
    expect(() =>
      extractSelectedColors(`${fixtureCss()}\n:root { --primary: #123456; }`)
    ).toThrow("Duplicate light --primary");
    expect(() =>
      extractSelectedColors(fixtureCss().replace("--primary: #aabbcc;", ""))
    ).toThrow("Missing dark --primary");
  });

  it("checks generated bytes read-only and catches actual selected-source drift", () => {
    const { root, source, output } = fixture();
    expect(() => runPortableColors("check", root)).toThrow("drift/missing");
    expect(runPortableColors("write", root).count).toBe(16);
    const original = readFileSync(output, "utf8");
    expect(runPortableColors("check", root).mode).toBe("check");
    expect(readFileSync(output, "utf8")).toBe(original);
    const tampered = original.replace("semantic", "semanticTampered");
    writeFileSync(output, tampered, "utf8");
    expect(() => runPortableColors("check", root)).toThrow("drift/missing");
    expect(readFileSync(output, "utf8")).toBe(tampered);
    writeFileSync(output, original, "utf8");
    writeFileSync(
      source,
      fixtureCss().replace("--card: #112233", "--card: #113355"),
      "utf8"
    );
    expect(() => runPortableColors("check", root)).toThrow("drift/missing");
    expect(readFileSync(output, "utf8")).toBe(original);
    expect(runPortableColors("write", root).mode).toBe("write");
    expect(runPortableColors("check", root).count).toBe(16);
  });

  it("rejects unsafe output targets and unknown command modes", () => {
    const { root, output } = fixture();
    mkdirSync(output);
    expect(() => runPortableColors("check", root)).toThrow(
      "Unsafe generated token artifact"
    );
    expect(() => runPortableColors("unknown" as "check", root)).toThrow(
      "Pass exactly"
    );
  });

  it("checks the real CSS owner and generated artifact without running a compiler", () => {
    const root = resolve(__dirname, "../../..");
    const document = buildPortableColors(
      readFileSync(join(root, SOURCE), "utf8")
    );
    expect(document.semantic.light.primary.$value.hex).toBe("#026699");
    expect(document.semantic.dark["primary-foreground"].$value.hex).toBe(
      "#0a1628"
    );
    expect(runPortableColors("check", root).count).toBe(16);
  });
});
